backy_back_messenger:
    resource: "@BackyBackMessengerBundle/Resources/config/routing.yml"
    prefix:   /messenger

backy_back_cookie_meet:
    resource: "@BackyBackCookieMeetBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
