backy_back_cookie_meet_homepage:
    path:     /
    defaults: { _controller: BackyBackCookieMeetBundle:Default:index }

backy_back_cookie_meet_admin:
    path:    /addservice
    type: rest
    resource: BackyBack\CookieMeetBundle\Controller\AddServiceController