backy_back_cookie_meet_homepage:
    path:     /
    defaults: { _controller: BackyBackCookieMeetBundle:Index:homepage }

backy_back_cookie_meet_users:
    path:     /users
    defaults: { _controller: BackyBackCookieMeetBundle:Index:users }

backy_back_cookie_meet_addservice:
    path:     /addservice
    defaults: { _controller: BackyBackCookieMeetBundle:AddService:AddService }

backy_back_cookie_meet_map:
    path:     /map
    defaults: { _controller: BackyBackCookieMeetBundle:Map:AddMap }

backy_back_cookie_meet_messenger:
    path:     /messenger
    defaults: { _controller: BackyBackCookieMeetBundle:Messenger:messenger }