backy_back_cookie_meet_home:
    path:     /
    defaults: { _controller: BackyBackCookieMeetBundle:Home:getHome }

backy_back_cookie_meet_recepee:
    path:     /recepee
    defaults: { _controller: BackyBackCookieMeetBundle:AddRecepee:AddRecepee }

backy_back_cookie_meet_messenger:
    path:     /messenger
    defaults: { _controller: BackyBackCookieMeetBundle:Messenger:getMessenger }

backy_back_cookie_meet_api_map:
    type: rest
    prefix: /api
    resource: BackyBack\CookieMeetBundle\Controller\MapController

backy_back_cookie_meet_api_messenger:
    type: rest
    prefix: /api
    resource: BackyBack\CookieMeetBundle\Controller\MessengerController

backy_back_cookie_meet_user:
    type: rest
    prefix: /api
    resource: BackyBack\CookieMeetBundle\Controller\UserAPIController