services:
    fos_user.doctrine_registry:
        alias: doctrine

services:
    app.form.registration:
        class: BackyBack\CookieMeetBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
            - { firstname: form.type, alias: app_user_registration }
            - { address: form.type, alias: app_user_registration }