<?php

namespace BackyBack\CookieMeetBundle\Repository;

/**
 * AddRecepeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddRecepeeRepository extends \Doctrine\ORM\EntityRepository
{
}
