<?php

namespace BackyBack\CookieMeetBundle\Repository;

/**
 * AddServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
