BackyBack\CookieMeetBundle\Entity\AddService:
    type: entity
    table: null
    repositoryClass: BackyBack\CookieMeetBundle\Repository\AddServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        plateName:
            type: string
            length: 255
            nullable: true
        plateCategory:
            type: string
            length: 255
            nullable: true
        platePrice:
            type: integer
            nullable: true
        plateExcerpt:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
